name: Build, Lint & Test Go

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  go-ci:
    runs-on: ubuntu-latest
    
    if: ${{ startsWith(github.head_ref, 'feature/') || startsWith(github.head_ref, 'hotfix/') || startsWith(github.head_ref, 'bugfix/') || github.head_ref == 'dev' || github.head_ref == 'staging' }}
    defaults:
      run:
        working-directory: Go   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' 
          
      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run code lints
        run: golangci-lint run ./...

      - name: Run unit tests
        run: go test -v ./...
