name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test-helloworld:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Code Chcekout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Python tools & Dependencies
        run: pip install ruff black mypy pytest

      - name: Run Code Lints
        run: ruff check .

      - name: Running Unit Test Cases
        

      
