name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test-helloworld:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          
      - name: Install tools
        run: |
          pip install ruff black mypy pytest
      
      - name: Lint with ruff
        run: ruff check .
