name: py-publish

on:
  pull_request:
    branches:
      - main
      - develop
      - release

  workflow_dispatch:
    inputs:
      env:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - uat
          - prod


jobs:
  Deploy-To-Dev:
      if: ${{ github.event.inputs.env == 'dev' }}
      runs-on: ubuntu-latest
      
      steps:
         - name: Checkout source code
           uses: actions/checkout@v4
               
      



