name: Publish to DEV Environment

on:
  push:
    branches:
      - Develop
  workflow_dispatch:
  
env:
  DOCKER_REGISTRY: ${{ secrets.ACR_REGISTRY }}
  IMAGE_NAME: ${{ secrets.USR_Image }}
  APP_NAME: Sampleapp


jobs:
  build-and-publish:
    name: Build and Push SNAPSHOT-1.0 docker Image
    if: >
       ( github.event_name == 'push' && github.ref == 'ref/heads/main' ) ||
       ( github.event_name == 'workflow_dispatch' && github.ref == 'refs/main' )

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run Lints and Code formatting
        uses: astral-sh/ruff-action@v3.5.1
        with:
          args: check .
          src: .
      
      - name: Build and Compile Code
        run: python -m compileall .

      - name: Running unit test cases
        run: python -m unittest 

        
      - name: Build Python package
        run: python -m build

  


