name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Enter Release Version (e.g., 1.0.1)"
        required: true
        default: "1.0.0"

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Release Branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" != release/* ]]; then
            echo "This pipeline can only run from a release/* branch."
            exit 1
          fi
          echo "Branch: $BRANCH_NAME"
          echo "Triggered by: $GITHUB_ACTOR"
          echo "Input Version: ${{ github.event.inputs.Version }}"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ruff Lints and Autoformat Check
        uses: astral-sh/ruff-action@v3.5.1
        with:
          args: check . --fix

      - name: Run Unit Tests and Coverage
        run: |
          coverage run -m unittest
          coverage report -m --fail-under=80

      - name: Compile Code
        run: python -m compileall .

  Release:
    needs: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Azure CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure Container Registry Login
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_ACR }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Get Latest Tag from ACR
        id: version_check
        run: |
          REPO_NAME="python_service"
          echo "Fetching latest tag for $REPO_NAME..."

          LATEST_TAG=$(az acr repository show-tags -n ${{ secrets.AZURE_ACR }} \
            --repository $REPO_NAME --orderby time_desc --output tsv | head -n 1)

          if [[ -z "$LATEST_TAG" ]]; then
            LATEST_TAG="none"
          fi

          echo "Latest tag in ACR: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT

          INPUT_VERSION="${{ github.event.inputs.Version }}"
          if [[ "$INPUT_VERSION" == "$LATEST_TAG" ]]; then
            echo "Version $INPUT_VERSION already exists in ACR. Aborting release."
            exit 1
          fi

      - name: Log workflow inputs
        run: |
          echo "Triggered by: $GITHUB_ACTOR"
          echo "Branch: $GITHUB_REF"
          echo "Input Version: ${{ github.event.inputs.Version }}"
          echo "Latest version in ACR: $LATEST_TAG"

      - name: Build Docker Image
        run: docker buildx build --load -t python_service:${{ github.event.inputs.Version }} .

      - name: Tag Docker Image for ACR
        run: docker tag python_service:${{ github.event.inputs.Version }} \
          ${{ secrets.AZURE_ACR }}.azurecr.io/python_service:${{ github.event.inputs.Version }}

      - name: Push Docker Image to ACR
        run: docker push ${{ secrets.AZURE_ACR }}.azurecr.io/python_service:${{ github.event.inputs.Version }}
