name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      Version:
        description: "Enter Release Version (e.g., 1.0.1)"
        required: true
        default: "1.0.0"

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Release Branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          if [[ "$BRANCH_NAME" != release/* ]]; then
            echo "This pipeline can only run from a release/* branch."
            exit 1
          fi
          echo "Branch: $BRANCH_NAME"
          echo "Triggered by: $GITHUB_ACTOR"
          echo "Input Version: ${{ github.event.inputs.Version }}"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Ruff Lints and Autoformat Check
        uses: astral-sh/ruff-action@v3.5.1
        with:
          args: check . --fix

      - name: Run Unit Tests and Coverage
        run: |
          coverage run -m unittest
          coverage report -m --fail-under=80

      - name: Compile Code
        run: python -m compileall .

  Release:
    needs: Build
    runs-on: ubuntu-latest
    env:
      AZURE_ACR: ${{ secrets.AZURE_ACR }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      SERVICE: ${{ secrets.SERVICE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory
        run: |
          pwd
          ls -R

      - name: Install Azure CLI
        uses: pietrobolcato/install-azure-cli-action@v1.0.1

      - name: Azure CLI Login
        run: az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
